# Generated by Django 5.1.1 on 2024-10-09 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('message_for', models.CharField(max_length=200000, null=True)),
                ('message_against', models.CharField(max_length=200000, null=True)),
            ],
        ),
    ]
