# Generated by Django 5.1.1 on 2024-10-13 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='message_against',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='period',
            name='message_for',
            field=models.TextField(null=True),
        ),
    ]
