# Generated by Django 5.1.2 on 2024-11-03 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0002_alter_period_message_against_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='period',
            options={'ordering': ['id']},
        ),
    ]
